import { Rank } from "../../utils/enums";
import { Power } from "../../utils/enums/Power";
import { PowerDetailType, PowerType } from "../../utils/types/PowerDetailType";
import { StandardRangeMelee } from "../weapons/Range";

export const Shootist: PowerDetailType = {
  key: Power.Shootist,
  name: "Shootist",
  currentPowerPoints: 0,
  variants: [
    {
      type: PowerType.Utility,
      name: "Ammo Whammy",
      powerPointCost: 3,
      activationModifier: 0,
      duration: 1,
      rankRequirement: Rank.Veteran,
      notes: `Bullet is considered a Heavy Weapon.`,
      ...StandardRangeMelee,
    },
    {
      type: PowerType.Utility,
      name: "Argent Agony",
      powerPointCost: 3,
      activationModifier: 0,
      duration: 1,
      rankRequirement: Rank.Veteran,
      notes: `Bullet affects a being as though it were composed of its Weakness. The hexslinger must know the specific Weakness when etching the rune.`,
      ...StandardRangeMelee,
    },
    {
      type: PowerType.Utility,
      name: "Bullet With Your Name on It",
      powerPointCost: 2,
      activationModifier: 0,
      duration: 1,
      rankRequirement: Rank.Seasoned,
      notes: `Bullet ignores 2 points of Cover.`,
      ...StandardRangeMelee,
    },
    {
      type: PowerType.Utility,
      name: "Ghost Bullet",
      powerPointCost: 1,
      activationModifier: 0,
      duration: 1,
      rankRequirement: Rank.Novice,
      notes: `Bullet inflicts nonlethal damage.`,
      ...StandardRangeMelee,
    },
    {
      type: PowerType.Utility,
      name: "Guiding Light",
      powerPointCost: 2,
      activationModifier: 0,
      duration: 1,
      rankRequirement: Rank.Seasoned,
      notes: `Bullet acts as a flare, Illuminating the area for 10 turns.`,
      ...StandardRangeMelee,
    },
    {
      type: PowerType.Utility,
      name: "Kentucky Windage",
      powerPointCost: 4,
      activationModifier: 0,
      duration: 1,
      rankRequirement: Rank.Heroic,
      notes: `Bullet has double the Range and ignores 2 points of penalties from any source.`,
      ...StandardRangeMelee,
    },
    {
      type: PowerType.Utility,
      name: "Knife Through Butter",
      powerPointCost: 1,
      activationModifier: 0,
      duration: 1,
      rankRequirement: Rank.Novice,
      notes: `Bullet has +4 AP.`,
      ...StandardRangeMelee,
    },
    {
      type: PowerType.Utility,
      name: "Loaded for Bear",
      powerPointCost: 1,
      activationModifier: 0,
      duration: 1,
      rankRequirement: Rank.Novice,
      notes: `Bullet adds +1 Die Type to the weapon's damage.`,
      ...StandardRangeMelee,
    },
    {
      type: PowerType.Utility,
      name: "Longbarrel Special",
      powerPointCost: 2,
      activationModifier: 0,
      duration: 1,
      rankRequirement: Rank.Seasoned,
      notes: `Bullet ignores 2 points of Range penalties.`,
      ...StandardRangeMelee,
    },
    {
      type: PowerType.Utility,
      name: "Sacramento Surprise",
      powerPointCost: 2,
      activationModifier: 0,
      duration: 1,
      rankRequirement: Rank.Seasoned,
      notes: `Bullet adds 1d6 of energy damage (acid, cold, electricity, fire, or sound).`,
      ...StandardRangeMelee,
    },
    {
      type: PowerType.Utility,
      name: "Segmented Shell",
      powerPointCost: 3,
      activationModifier: 0,
      duration: 1,
      rankRequirement: Rank.Veteran,
      notes: `Bullet explodes when it strikes a target, inflicting its damage in a Medium Burst Template.`,
      ...StandardRangeMelee,
    },
    {
      type: PowerType.Utility,
      name: "Shrapnel Storm",
      powerPointCost: 4,
      activationModifier: 0,
      duration: 1,
      rankRequirement: Rank.Heroic,
      notes: `Bullet sprays shrapnel in all directions when it strikes a target, inflicting its damage in a Large Burst Template and counts as a Heavy Weapon.`,
      ...StandardRangeMelee,
    },
    {
      type: PowerType.Utility,
      name: "Spherical Shell",
      powerPointCost: 2,
      activationModifier: 0,
      duration: 1,
      rankRequirement: Rank.Seasoned,
      notes: `Bullet fragments when it strikes a target, inflicting its damage in a Small Burst Template.`,
      ...StandardRangeMelee,
    },
  ],
};
