export enum Edge {
  Alertness = "Alertness",
  Ambidextrous = "Ambidextrous",
  ArcaneBackgroundMagic = "ArcaneBackgroundMagic",
  ArcaneBackgroundMiracles = "ArcaneBackgroundMiracles",
  ArcaneBackgroundShamanism = "ArcaneBackgroundShamanism",
  ArcaneBackgroundChiMastery = "ArcaneBackgroundChiMastery",
  ArcaneBackgroundWeirdScience = "ArcaneBackgroundWeirdScience",
  ArcaneResistance = "ArcaneResistance",
  ArcaneResistanceImproved = "ArcaneResistanceImproved",
  Attractive = "Attractive",
  AttractiveVery = "AttractiveVery",
  Berserk = "Berserk",
  Brave = "Brave",
  Brawny = "Brawny",
  FastHealer = "FastHealer",
  FleetFooted = "FleetFooted",
  GallowsHumor = "GallowsHumor",
  Linguist = "Linguist",
  Luck = "Luck",
  LuckGreat = "LuckGreat",
  Quick = "Quick",
  Rich = "Rich",
  RichFilthy = "RichFilthy",

  BlindFighting = "BlindFighting",
}
