export enum Power {
  Armor = "Armor",
  Barrier = "Barrier",
  Bolt = "Bolt",
  BoostLowerTrait = "BoostLowerTrait",
  Burst = "Burst",
  ElementalManipulationEarth = "ElementalManipulationEarth",
  Healing = "Healing",
  Hunch = "Hunch",
  MindReading = "MindReading",
  ShapeChange = "ShapeChange",
  Shootist = "Shootist",
  Slumber = "Slumber",
  Smite = "Smite",
  Telekinesis = "Telekinesis",
}
