export enum Skill {
  Boating = "Boating",
  Climbing = "Climbing",
  Faith = "Faith",
  Fighting = "Fighting",
  Investigation = "Investigation",
  KnowledgeScience = "KnowledgeScience",
  KnowledgeOccult = "KnowledgeOccult",
  Lockpicking = "Lockpicking",
  Notice = "Notice",
  Persuasion = "Persuasion",
  Repair = "Repair",
  Riding = "Riding",
  Shooting = "Shooting",
  Stealth = "Stealth",
  Streetwise = "Streetwise",
  Taunt = "Taunt",
  Tracking = "Tracking",
  WeirdScience = "WeirdScience",
}
