export enum Weapon {
  Bow = "Bow",
  BowieKnife = "BowieKnife",
  ColtArmy = "ColtArmy",
  ColtDragoon = "ColtDragoon",
  ColtPeacemakerSingle = "ColtPeacemakerSingle",
  ColtPeacemakerDouble = "ColtPeacemakerDouble",
  ElectricRapier = "ElectricRapier",
  GatlingPistol = "GatlingPistol",
  HastelisWarClub = "HastelisWarClub",
  HellstrommesCane = "HellstrommesCane",
  HornOfAlquahata = "HornOfAlquahata",
  LeMatGrapeshotDouble = "LeMatGrapeshotDouble",
  LeMatGrapeshotShotgun = "LeMatGrapeshotShotgun",
  Swordcane = "Swordcane",
  Tomahawk = "Tomahawk",
  UnhallowedBlade = "UnhallowedBlade",
}
