name: Build on PR

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  jest:
    runs-on: ubuntu-latest
    name: Build
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v2
      - name: Build project
        run: |
          npm i
          npm run build
